#!/bin/bash
#SBATCH --export=ALL
#SBATCH -N 1 # numero de nodos
#SBATCH -t 60 # tempo maximo de execucao: 5min
#SBATCH --exclusive
#SBATCH --no-requeue
#SBATCH -o /home/pp03011/openmp/parallel_bubble/exit/%x.%j_static_8_500.out -e /home/pp03011/openmp/parallel_bubble/exit/%x.%j_static_8_500.err # formato do nome do arquivo de saída
#SBATCH -D /home/pp03011/openmp/parallel_bubble # diretório
echo ################
echo Running on host `hostname`
echo
echo Initial Time is `date`
echo
echo Directory is `pwd`
echo
echo This jobs runs on the following nodes:
echo $SLURM_JOB_NODELIST
echo
echo JOB_ID:
echo $SLURM_JOBID
echo ################
./static/bubble_static_8_500 > ./static/report/saida_static_8_500.output
